install:
    - wget http://www.gsptalk.com/mirror/sourcemod/sourcemod-1.5.3-linux.tar.gz
    - tar -zxvf sourcemod-1.5.3-linux.tar.gz
before_script:
    - ls #Let's see where we are
script:
    - addons/sourcemod/scripting/compile.sh class_warfare.sp